grafana:
  adminPassword: admin
  persistence:
    enabled: true
    size: 10Gi
  
prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'sns'
    receivers:
    - name: 'sns'
      sns_configs:
      - topic_arn: ${sns_topic_arn}
        region: ${aws_region}
